# Generated by Django 5.1.6 on 2025-03-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
